name: Update Terminal Animation
on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ "main", "master" ]
    paths:
      - 'README.md'
      - '.github/workflows/terminal-stats.yml'
      - '.github/scripts/generate_terminal_gif.py'

jobs:
  update-terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub Pillow imageio beautifulsoup4

      - name: Fetch GitHub stats and generate GIF
        run: |
          python .github/scripts/generate_terminal_gif.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update terminal animation" && git push)
